### ISSUE TITLE
Share Code - Feature Request

### ISSUE THREAD

**Issue by dieskim** [mufri/Authenticator-Plus#2]
It would be great to be able to share codes - maybe another option where the logo/rename options are? It would be very simple to just generate an QR code based on the entry then another user could scan that QR code on his phone to get the entry on his phone as well.

**Comment by MufriA** [comment]
You can do this using Authenticator Plus -> Settings -> Backup & Restore -> Export as Text and Html

Its not straight forward as generating QR code in app itself but this is the workaround.
